version: 0.0
os: linux

files:
  - source: app.jar
    destination: /home/ec2-user/app
  - source: scripts/
    destination: /home/ec2-user/app/scripts

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: ec2-user

  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ec2-user
